[package]
name = "vault-core"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
vault-bitcoin = { path = "../vault-bitcoin" }
vault-crypto = { path = "../vault-crypto" }
vault-network = { path = "../vault-network" }
vault-monero = { path = "../vault-monero" }
vault-policy = { path = "../vault-policy" }
vault-storage = { path = "../vault-storage" }
vault-swap = { path = "../vault-swap" }
vault-signing = { path = "../vault-signing" }
vault-zcash = { path = "../vault-zcash" }
